# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 647da4b25eb4c1b1ec524a7c21b88119c4fcc0067f10764239cd125065bfa3510b1df3fc3f03d1c87fa131fb32e72a018bb394bd9a138db4098dc4d86b67db7a

test:
  secret_key_base: 6496029e107eee20b85325c74ee34b544fa8783b848f8dcb5167570dc59c6858bb360dd16bfbb0494ac9c7f966e40ca4283d114ab6ae14928cd30fc4f6979b5d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
